# base layer - starting from an existing image
FROM python:3.13
#instraction layer _ where we will start in the container
WORKDIR /app
# instraction layer _ copies everything from this floder in host system into /app
COPY . . 
# instraction layer - installing packages (runs bash command)
RUN pip install -r requirements.txt 
# instraction layer - bash command to run when container is spun up
CMD [ "python", "main.py" ]



